services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: votacao_rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"     # AMQP (clients)
      - "15672:15672"   # Management UI (web)
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq

volumes:
  rabbitmq_data:
  rabbitmq_logs:
